# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-output name=files::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            -s manuscript.tex
            -o output/manuscript.md
            
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
