# This is a basic workflow to help you get started with Actions

name: tex2pdf

on: [push]

jobs:
  build-tex:
    runs-on: ubuntu-latest
    name: tex2pdf
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Convert to pdf
      id: convert-to-pdf
      uses: closoco/pdflatex-action@v1.0.0
      with:
        texFile: manuscript.tex
    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: manuscript.pdf
        path: manuscript.pdf


